### ISSUE TITLE
support enabling TLSv1.2 on Android 4.1-4.4.

### ISSUE THREAD

**Issue by mlc** [square/okhttp#2372]
Our lawyers and security consultants claim that for [PCI][] compliance*, we must disable TLS 1.0 and 1.1 on our servers. For some confusing reason, Android has _supported_ TLS 1.2 [since API 16 (android 4.1) but enabled it by default only since API 20 (android "4.4W")][SSLSocket].

With okhttp 2.6, we were able to force use of TLS 1.2 with:
```java
OkHttpClient cli = new OkHttpClient();
SSLContext sc = SSLContext.getInstance("TLSv1.2");
sc.init(null, null, null);
cli.setSslSocketFactory(new Tls12SocketFactory(sc.getSocketFactory()));
ConnectionSpec cs = new ConnectionSpec.Builder(ConnectionSpec.MODERN_TLS)
        .tlsVersions(TlsVersion.TLS_1_2)
        .build();
cli.setConnectionSpecs(ImmutableList.of(cs));
```
where `Tls12SocketFactory` is [this][gist].

However, okhttp 3.1 uses some kind of reflection on internal implementation details of the `SSLSocketFactory`, so the above implementation [no longer works][err]. And, indeed, it's a bit silly to make callers write so much code anyway. Specifying `TLS_1_2` in the `ConnectionSpec` should be enough to get TLSv1.2 whenever it is supported.

As far as I can tell, the only reason why the custom socket factory is needed in the first place is that `ConnectionSpec.supportedSpec()` [calls `SSLSocket.getEnabledProtocols()`][getenabled] to learn the list of protocols supported by the system, so on Android 4._x_ where TLS 1.2 is supported but not enabled by default, OkHttp thinks 1.2 is not supported at all.

Sorry for this long bug report: I _think_ the fix is as simple as changing `getEnabledProtocols()` above to `getSupportedProtocols()` but wanted to submit this bug for discussion before making a PR with such a change, in case there is some affirmative reason why it's the other way now.

\* Originally I understood the PCI compliance deadline to be June 2016; however, it seems like it has since [been changed][] to be June 2018. Regardless, OkHttp should support this change for users that want it.
[PCI]: https://en.wikipedia.org/wiki/Payment_Card_Industry_Data_Security_Standard
[SSLSocket]: http://developer.android.com/reference/javax/net/ssl/SSLSocket.html
[gist]: https://gist.github.com/mlc/549409f649251897ebef
[been changed]: http://blog.pcisecuritystandards.org/migrating-from-ssl-and-early-tls
[err]: https://gist.github.com/mlc/a0f43fa0b15a8f96244b
[getenabled]: https://github.com/square/okhttp/blob/parent-3.1.2/okhttp/src/main/java/okhttp3/ConnectionSpec.java#L145-L150

**Comment by swankjesse** [comment]
As a quick fix, try renaming the `SSLSocketFactory` field in `Tls12SocketFactory` to `delegate`. It’s a gross hack, and it’s sad, and it’s how we cope with the absence of the APIs we need doing fancy TLS in Java.

**Comment by swankjesse** [comment]
No action for us to take here.

**Comment by gotev** [comment]
Had the same issue on Android < 5.0 (16 <= API < 21). Thanks to your posts, I was able to make this work, so for anyone who gets here, this is the out-of-the-box solution. At the time of this writing, I'm using `OkHttp 3.4.1`.

Add `Tls12SocketFactory.java` with the following content:
```java
import java.io.IOException;
import java.net.InetAddress;
import java.net.Socket;
import java.net.UnknownHostException;

import javax.net.ssl.SSLSocket;
import javax.net.ssl.SSLSocketFactory;

/**
 * Enables TLS v1.2 when creating SSLSockets.
 * <p/>
 * For some reason, android supports TLS v1.2 from API 16, but enables it by
 * default only from API 20.
 * @link https://developer.android.com/reference/javax/net/ssl/SSLSocket.html
 * @see SSLSocketFactory
 */
public class Tls12SocketFactory extends SSLSocketFactory {
    private static final String[] TLS_V12_ONLY = {"TLSv1.2"};

    final SSLSocketFactory delegate;

    public Tls12SocketFactory(SSLSocketFactory base) {
        this.delegate = base;
    }

    @Override
    public String[] getDefaultCipherSuites() {
        return delegate.getDefaultCipherSuites();
    }

    @Override
    public String[] getSupportedCipherSuites() {
        return delegate.getSupportedCipherSuites();
    }

    @Override
    public Socket createSocket(Socket s, String host, int port, boolean autoClose) throws IOException {
        return patch(delegate.createSocket(s, host, port, autoClose));
    }

    @Override
    public Socket createSocket(String host, int port) throws IOException, UnknownHostException {
        return patch(delegate.createSocket(host, port));
    }

    @Override
    public Socket createSocket(String host, int port, InetAddress localHost, int localPort) throws IOException, UnknownHostException {
        return patch(delegate.createSocket(host, port, localHost, localPort));
    }

    @Override
    public Socket createSocket(InetAddress host, int port) throws IOException {
        return patch(delegate.createSocket(host, port));
    }

    @Override
    public Socket createSocket(InetAddress address, int port, InetAddress localAddress, int localPort) throws IOException {
        return patch(delegate.createSocket(address, port, localAddress, localPort));
    }

    private Socket patch(Socket s) {
        if (s instanceof SSLSocket) {
            ((SSLSocket) s).setEnabledProtocols(TLS_V12_ONLY);
        }
        return s;
    }
}
```

Then, add this method somewhere in your code:
```java
public static OkHttpClient.Builder enableTls12OnPreLollipop(OkHttpClient.Builder client) {
    if (Build.VERSION.SDK_INT < 21) {
        try {
            SSLContext sc = SSLContext.getInstance("TLSv1.2");
            sc.init(null, null, null);
            client.sslSocketFactory(new Tls12SocketFactory(sc.getSocketFactory()));

            ConnectionSpec cs = new ConnectionSpec.Builder(ConnectionSpec.MODERN_TLS)
                    .tlsVersions(TlsVersion.TLS_1_2)
                    .build();

            List<ConnectionSpec> specs = new ArrayList<>();
            specs.add(cs);
            specs.add(ConnectionSpec.COMPATIBLE_TLS);
            specs.add(ConnectionSpec.CLEARTEXT);

            client.connectionSpecs(specs);
        } catch (Exception exc) {
            Log.e("OkHttpTLSCompat", "Error while setting TLS 1.2", exc);
        }
    }

    return client;
}
```

And when you create your `OkHttp` instance, use it for example like this:
```java
private static OkHttpClient getHttpClient() {
    OkHttpClient.Builder client = new OkHttpClient.Builder()
            .followRedirects(true)
            .followSslRedirects(true)
            .retryOnConnectionFailure(true)
            .cache(null)
            .connectTimeout(5, TimeUnit.SECONDS)
            .writeTimeout(5, TimeUnit.SECONDS)
            .readTimeout(5, TimeUnit.SECONDS);

    return enableTls12OnPreLollipop(client).build();
}
```

**Comment by meyn** [comment]
@gotev thanks for sharing, any particular reason you've added the `COMPATIBLE_TLS` and `CLEARTEXT` in your connection specs? aren't these necessary only if you want to allow fallbacks to older TLS versions / cleartext http?

**Comment by yoavgrosswild** [comment]
Seems like client.sslSocketFactory(sslSocketFactory) is deprecated and the documentation recommends using client.sslSocketFactory(sslSocketFactory, X509TrustManager trustManager). How do i get an X509TrustManager object? just create new ?

**Comment by swankjesse** [comment]
https://square.github.io/okhttp/3.x/okhttp/okhttp3/OkHttpClient.Builder.html#sslSocketFactory-javax.net.ssl.SSLSocketFactory-javax.net.ssl.X509TrustManager-

**Comment by cantek41** [comment]
SSLContext sslContext = SSLContext.getInstance("TLSv1.2");
                TrustManager[] trustManagers = new TrustManager[] { new TrustManagerManipulator() };
                sslContext.init(null, trustManagers, new SecureRandom());               
                SSLSocketFactory noSSLv3Factory = new TLSSocketFactory(sslContext.getSocketFactory());
                urlConnection.setSSLSocketFactory(noSSLv3Factory);

https://github.com/IKANOW/Infinit.e/blob/master/core/infinit.e.data_model/src/com/ikanow/infinit/e/data_model/utils/TrustManagerManipulator.java

**Comment by aquakul** [comment]
Slightly unrelated. But once I make the changes, how do I actually confirm that app and server are indeed using TLS 1.2 (on my server TLS 1.0, 1.1 and 1.2 all are enabled). Is there a hint in the HTTP packet ?

**Comment by swankjesse** [comment]
Check the Handshake object on the Response.

**Comment by lorenzowoodridge** [comment]
Has anyone actually come up with a working solution for KitKat?

**Comment by techiebrij** [comment]
Struggling with same issue with TLS1.2 support on API 19? Does anyone have working solution yet?

**Comment by YamilMarques** [comment]
Same problem here...

**Comment by StuStirling** [comment]
@techiebrij any luck with the error? I am experiencing something similiar.

[W: javax.net.ssl.SSLHandshakeException: javax.net.ssl.SSLProtocolException: SSL handshake aborted: ssl=0x5cb59b30: Failure in SSL library, usually a protocol error
W: error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure (external/openssl/ssl/s23_clnt.c:744 0x5cbd77e8:0x00000000)
W: javax.net.ssl.SSLHandshakeException: javax.net.ssl.SSLProtocolException: SSL handshake aborted: ssl=0x65211a70: Failure in SSL library, usually a protocol error
W: error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure (external/openssl/ssl/s23_clnt.c:744 0x5cbd77e8:0x00000000)
W:     at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:449)](url)

**Comment by Macarse** [comment]
@gotev why `Build.VERSION.SDK_INT < 22` and not `Build.VERSION.SDK_INT < 20`?

**Comment by volodyad** [comment]
Tried @gotev solution and also get SSL23_GET_SERVER_HELLO:sslv3 , why does it fallback to sslv3?

**Comment by techiebrij** [comment]
@StuStirling, sorry for responding late. @gotev code will work only when web server supports right cipher. You can get the list of supported ciphers here https://developer.android.com/reference/javax/net/ssl/SSLEngine.html

API-19 out of code can't do anything to make it work as it has dependency on network call (web server with different SSL spec).

**Comment by StuStirling** [comment]
Thanks @techiebrij.

For anyone else that may be struggling with this, the thing that fixed mine was to install the latest security fixes that are bundled with Google Play Services.

`ProviderInstaller.installIfNeeded(context);`

After doing this, the solution for enabling TLS1.2 worked.

**Comment by gotev** [comment]
API < 22 was used because of some samsung devices which needed those settings, too. Bear in mind the certificate problem is not only a client side thing. Ensure you have good certificates from well known CAs if you plan to support API < 19.

**Comment by savepopulation** [comment]
@gotev i used your code you gave above but almost %1 of my pre-lolliop user's gets exception while setting TLS1.2. is it normal? do you suggest any workaround to handle this problem?

**Comment by gotev** [comment]
I've seen this happening on a bunch of old samsung devices with API < 19. Solved by using a well known CA for my server side certificates, no changes in actual code.

**Comment by kounalem** [comment]
Is there another fix available for on the sslv3 fallback occurring without having to install the Google Play Services?

**Comment by casadogg** [comment]
I give up. After doing everything listed in this thread (Using TLS12SocketFactory, updating google play services, forcing security fixes, adding safe ciphers to the server side), several devices (mainly old Samsung and old rooted devices) are still getting this problem.

Now I'm using Fabric to log devices having issues connecting to our server, as well as their cipher suites. Worst case scenario, I'll just block these devices from being able to download the app from the store. Shitty solution, but it is what it is.

**Comment by gotev** [comment]
The problem is that those devices don't have what's needed for TLS 1.2. What I ended up doing, and I'm not the only one, is to add older ciphers to the certificate and display a big warning on those devices when I detected they did not support TLS 1.2, informing users that in N months from that message, new TLS 1.2 will be the only standard allowed. After that period, I still allowed users to download the app, but once started it does all the necessary checks and informs the users about the security issue. Maybe it's not the best possible solution, but all depends on how much audience are you impacting.

**Comment by perrosnk** [comment]
Any updates on this?

**Comment by kounalem** [comment]
Hi @perrosnk. I solved it by using the [bounty castle](https://www.google.gr/search?q=bounty+castle+java&oq=bountycastle&aqs=chrome.2.69i57j0l5.3599j0j7&sourceid=chrome&ie=UTF-8) jar file. Give it a chance :)

**Comment by mniami** [comment]
Works on my side using @StuStirling solution. API 17, HTC X One.

**Comment by kounalem** [comment]
@mniami This is not a solution. What happens if someone cannot access google play services for a reason? :-)

**Comment by mniami** [comment]
Do you have @kounalem working solution without forcing user to update GPS?

**Comment by perrosnk** [comment]
@StuStirling  Where do you pull the context from ?
Can you share an example of how to use this code?

@kounalem Thank you for your help. Your solution seems nice, but I have no idea how to use it. Actually I am developing in react-native.

**Comment by KOLANICH** [comment]
https://github.com/guardianproject/NetCipher

**Comment by StuStirling** [comment]
Could this be solution? Using bouncy castle to enable TLS1.2? https://stackoverflow.com/questions/33517476/tls-1-2-java-1-6-bouncycastle

**Comment by sergiomarquesmoura** [comment]
Any effective fix on this? I tried multiple approaches, concretely every one described in this thread plus many of the ones described in the issues that link to this one. And still no luck.

My use case is that I would like to restrict TLS to 1.2 only and I would prefer to do this without having to include Google Play Services (currently not using and the less dependencies the better)

It's crazy that the newer TLS versions were introduced without a proper non-hacky way of enabling them being added as well.

**Comment by swankjesse** [comment]
You could figure out how to repackage Conscrypt and ship that.

**Comment by rizwan321** [comment]
i am also facing 


javax.net.ssl.SSLProtocolException: SSL handshake aborted: ssl=0xb4068200: Failure in SSL library, usually a protocol error
error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure (external/openssl/ssl/s23_clnt.c:770 0xabeeddd4:0x00000000)

any one have solution ???

**Comment by yschimke** [comment]
@rizwan321 Please ask usage questions like this on stackoverflow.

IF you think you have found a bug, please include a test case or code to reproduce it, e.g. connecting against a test server we can access.

**Comment by thuytrinh** [comment]
The patch in https://github.com/square/okhttp/issues/2372#issuecomment-331623598 actually worked for us.

**Comment by Zo2m4bie** [comment]
Hello. I tried solution provided by @gotev and @lucaskuan 
I tested TLS on
https://api.fastly.com/public-ip-list
https://tlstest.paypal.com/
However on my website I still receive error
```
javax.net.ssl.SSLProtocolException: SSL handshake aborted: ssl=0xb950bc70: Failure in SSL library, usually a protocol error
error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure (external/openssl/ssl/s23_clnt.c:744 0x9c8367f1:0x00000000)
```
My urls works fine on android 5. I found clipper on my api use the same clipper as tested ones TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256S So it should work but it's not. 
Does anyone know what can be the reason?

**Comment by Zo2m4bie** [comment]
@lucaskuan 
But I can't understand how these work:
https://api.fastly.com/public-ip-list
https://tlstest.paypal.com/
They use TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256 too

**Comment by KeyStarr** [comment]
I was facing that very same issue while using Glide. I tried to combine solutions from this discussions and some others, but was unsuccessfull. 
However i found a working solution for enabling TSL v1.2 for okhttp 3 with glide, here it is: (as i see also based on thought from this thread)
https://developer.android.com/reference/javax/net/ssl/SSLSocket

I am not sure whether my comment appropriate since it is an okhttp rep, but despite glide references one can still extract working okhttp-only solution.

**Comment by skauss** [comment]
@gotev Thank you for your example

**Comment by malikhzr** [comment]
> SSLContext sslContext = SSLContext.getInstance("TLSv1.2");
> TrustManager[] trustManagers = new TrustManager[] { new TrustManagerManipulator() };
> sslContext.init(null, trustManagers, new SecureRandom());
> SSLSocketFactory noSSLv3Factory = new TLSSocketFactory(sslContext.getSocketFactory());
> urlConnection.setSSLSocketFactory(noSSLv3Factory);
> 
> https://github.com/IKANOW/Infinit.e/blob/master/core/infinit.e.data_model/src/com/ikanow/infinit/e/data_model/utils/TrustManagerManipulator.java

"urlConnection.setSSLSocketFactory(noSSLv3Factory);" Hi, where do you initialize urlConnection before using to setSSLSocketFactory???

**Comment by skauss** [comment]
@malikhzr 
I do it this way 
```
                SSLContext sc = SSLContext.getInstance("TLSv1.2");
                sc.init(null, null, null);
                client.sslSocketFactory(new Tls12SocketFactory(sc.getSocketFactory()));

                ConnectionSpec cs = new ConnectionSpec.Builder(ConnectionSpec.MODERN_TLS)
                        .tlsVersions(TlsVersion.TLS_1_2)
                        .build();

                List<ConnectionSpec> specs = new ArrayList<>();
                specs.add(cs);
                specs.add(ConnectionSpec.COMPATIBLE_TLS);
                specs.add(ConnectionSpec.CLEARTEXT);

                client.connectionSpecs( Collections.unmodifiableList( specs));
```

**Comment by malikhzr** [comment]
@skauss  Thank you for reply. But isn't client.sslSocketFactory deprecated? I am gonna try your code anyway.

**Comment by malikhzr** [comment]
React Native version 0.55.4
I implemented everything inside MainActivity.java. I used your code but still it didn't enable TLS version 1.2. Still it is not working on Android Lollipop 5.0.1

package com.dialogNow;

import com.facebook.react.ReactActivity;
import org.devio.rn.splashscreen.SplashScreen;
import android.os.Bundle;
import java.util.*;

import android.util.Log;
import com.facebook.react.modules.network.OkHttpClientProvider;
import com.facebook.react.modules.network.ReactCookieJarContainer;
import okhttp3.ConnectionSpec;
import okhttp3.OkHttpClient;
import okhttp3.TlsVersion;

import javax.net.ssl.*;
import java.util.Arrays;
import java.util.concurrent.TimeUnit;

import java.io.IOException;
import java.net.InetAddress;
import java.net.Socket;
import java.net.UnknownHostException;

import javax.net.ssl.SSLSocket;
import javax.net.ssl.SSLSocketFactory;

public class MainActivity extends ReactActivity {
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        SplashScreen.show(this, R.style.SplashTheme);  // here
        super.onCreate(savedInstanceState);
        getNewHttpClient();
    }

    /**
     * Returns the name of the main component registered from JavaScript.
     * This is used to schedule rendering of the component.
     */
    @Override
    protected String getMainComponentName() {
        return "demo";
    }

    private OkHttpClient getNewHttpClient() {
    OkHttpClient.Builder client = new OkHttpClient.Builder()
            .followRedirects(true)
            .followSslRedirects(true)
            .retryOnConnectionFailure(true)
            .cache(null)
            .connectTimeout(5, TimeUnit.SECONDS)
            .writeTimeout(5, TimeUnit.SECONDS)
            .readTimeout(5, TimeUnit.SECONDS);

    return enableTls12OnPreLollipop(client).build();
    }
        

    public  OkHttpClient.Builder enableTls12OnPreLollipop(OkHttpClient.Builder client) {
        // if (Build.VERSION.SDK_INT >= 16 && Build.VERSION.SDK_INT < 22) {
            try {
                SSLContext sc = SSLContext.getInstance("TLSv1.2");
                sc.init(null, null, null);
                client.sslSocketFactory(new Tls12SocketFactory(sc.getSocketFactory()));

                ConnectionSpec cs = new ConnectionSpec.Builder(ConnectionSpec.MODERN_TLS)
                        .tlsVersions(TlsVersion.TLS_1_2)
                        .build();

                List<ConnectionSpec> specs = new ArrayList<>();
                specs.add(cs);
                specs.add(ConnectionSpec.COMPATIBLE_TLS);
                specs.add(ConnectionSpec.CLEARTEXT);

                client.connectionSpecs( Collections.unmodifiableList( specs));
            } catch (Exception exc) {
                Log.e("OkHttpTLSCompat", "Error while setting TLS 1.2", exc);
            }
        // }

        return client;
    }

    class Tls12SocketFactory extends SSLSocketFactory {
        private String[] TLS_V12_ONLY = {"TLSv1.2"};

        final SSLSocketFactory delegate;

        public Tls12SocketFactory(SSLSocketFactory base) {
            this.delegate = base;
        }

        @Override
        public String[] getDefaultCipherSuites() {
            return delegate.getDefaultCipherSuites();
        }

        @Override
        public String[] getSupportedCipherSuites() {
            return delegate.getSupportedCipherSuites();
        }

        @Override
        public Socket createSocket(Socket s, String host, int port, boolean autoClose) throws IOException {
            return patch(delegate.createSocket(s, host, port, autoClose));
        }

        @Override
        public Socket createSocket(String host, int port) throws IOException, UnknownHostException {
            return patch(delegate.createSocket(host, port));
        }

        @Override
        public Socket createSocket(String host, int port, InetAddress localHost, int localPort) throws IOException, UnknownHostException {
            return patch(delegate.createSocket(host, port, localHost, localPort));
        }

        @Override
        public Socket createSocket(InetAddress host, int port) throws IOException {
            return patch(delegate.createSocket(host, port));
        }

        @Override
        public Socket createSocket(InetAddress address, int port, InetAddress localAddress, int localPort) throws IOException {
            return patch(delegate.createSocket(address, port, localAddress, localPort));
        }

        private Socket patch(Socket s) {
            if (s instanceof SSLSocket) {
                ((SSLSocket) s).setEnabledProtocols(TLS_V12_ONLY);
            }
            return s;
        }
    }

}

**Comment by malikhzr** [comment]
@skauss am I missing something ?

**Comment by skauss** [comment]
@malikhzr 
Yes sslSocketFactory is deprecated.
Hm your code look similar to my one. My code work on 4.4.2.
Are you sure you use your  patched OkHttpClient ?

**Comment by malikhzr** [comment]
> @malikhzr
> Yes sslSocketFactory is deprecated.
> Hm your code look similar to my one. My code work on 4.4.2.
> Are you sure you use your patched OkHttpClient ?

@skauss How to ckeck if I am using patched OkHttpClient ? Or can you reference me some?

**Comment by skauss** [comment]
@malikhzr 
Use the debugger to be sure your client is used or add Log to your code.

**Comment by malikhzr** [comment]
@skauss  How to patch the OkHttpClient. 

I'm calling the getNewHttpClient() method in onCreate function. 

```
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        getNewHttpClient();

    }
```

**Comment by 3c71** [comment]
> ```java
> OkHttpClient.Builder
> ```

Thanks for this solution (gotev on Sep 5th 2016), allowed me to make it work on Android 4.x up-to 5.0.

That said, it didn't work out of the box because this solution doesn't work with servers having self-signed certificates. I had to change the init into this:

`sslContext.init(null, trustAllCerts, new java.security.SecureRandom());`

Also, the connectionSpecs() call turned out to be useless.

**Comment by gotev** [comment]
@3c71 instead of self signed, use https://letsencrypt.org/

**Comment by 3c71** [comment]
@gotev, thanks, however I don't use okhttp to connect to my own site, which I have a valid certificate for. I'm obviously referring to all those sites with self-signed certificates, like all those routers or NAS out there which can't actually be accessed with HTTPs unless certificate is either trusted automatically or manually confirmed. In both cases, it's mandatory to change the init() call.

**Comment by mirh** [comment]
> No action for us to take here.

Ehrm.. I don't want to be that guy, but why did you decide to [drop](https://github.com/square/okhttp/pull/4508) older android versions altogether? (rather than enabling this)
Is it just because of your [policy](https://github.com/square/okhttp/issues/2259#issuecomment-186975716) of "only defaults"?
Or were those 200 lines of code becoming that much of a burden (despite even the possibility of the conscrypt embedding)?

And I mean, it's not even like the market for this wouldn't be there given the number of referenced issues above.

**Comment by swankjesse** [comment]
Square doesn't ship software on Android 4.4 and I don’t want to do the work to test & support a platform I don’t use. In addition to 200 lines of code, there’s also code to integrate Conscrypt. Conscrypt is native code and there’s cost to making that work reliably everywhere.

I expect that if anyone really cared enough, they’d maintain an unofficial backport!  @mirh is that you?

**Comment by c4augustus** [comment]
We have slammed into this problem as well because we are providing a free healthcare app to a poor part of the world where many suffering users can only afford a Samsung J1 Ace that is stuck on an non-upgradeable Android 4.4. So lack of support for older Androids turns out to be a rest-of-the-world-problem rather than a first-world-problem.

**Comment by swankjesse** [comment]
@c4augustus some options to consider:

 * Get TLSv1.2 via the Google Play Services TLS provider. This requires your users have Google Play devices. You may also need to put UI in your app to prompt users to update Play Services if necessary. And then you just configure it before making an HTTPS call.

 * Get TLSv1.2 via Conscrypt. This requires you ship the TLS native code in your application, and configure it before you make an HTTPS call.

 * Change your HTTPS server to accept TLSv1.1. There are potential security consequences to this. But if your server supports both TLSv1.1 and TLSv1.2 it’s likely to not harm security for the TLSv1.2-capable devices.

**Comment by kairusds** [comment]
> @c4augustus some options to consider:
> 
> * Get TLSv1.2 via the Google Play Services TLS provider. This requires your users have Google Play devices. You may also need to put UI in your app to prompt users to update Play Services if necessary. And then you just configure it before making an HTTPS call.
> * Get TLSv1.2 via Conscrypt. This requires you ship the TLS native code in your application, and configure it before you make an HTTPS call.
> * Change your HTTPS server to accept TLSv1.1. There are potential security consequences to this. But if your server supports both TLSv1.1 and TLSv1.2 it’s likely to not harm security for the TLSv1.2-capable devices.

Quick question: how do I configure Conscrypt?

**Comment by c4augustus** [comment]
Here is how I fixed this for our app. Sorry that these are screenshots, but our repo is private.
<img width="890" alt="Screenshot 2021-09-13 at 11 09 51" src="https://user-images.githubusercontent.com/5049680/133066567-b01affd4-6dc8-45dc-9226-791bf11d49f5.png">
<img width="873" alt="Screenshot 2021-09-13 at 11 10 25" src="https://user-images.githubusercontent.com/5049680/133066616-39748f9c-5061-48c5-a2d3-f42fcbdbd612.png">
<img width="869" alt="Screenshot 2021-09-13 at 11 10 53" src="https://user-images.githubusercontent.com/5049680/133066635-c6d9c374-0fff-4958-a1d5-12ef2f105e3a.png">
<img width="872" alt="Screenshot 2021-09-13 at 11 11 09" src="https://user-images.githubusercontent.com/5049680/133066652-a085643c-8093-49be-89da-fb90a2c9f25e.png">
<img width="872" alt="Screenshot 2021-09-13 at 11 11 45" src="https://user-images.githubusercontent.com/5049680/133066672-42be87ba-469b-4481-bac6-ac9a2c10d76d.png">
<img width="868" alt="Screenshot 2021-09-13 at 11 12 11" src="https://user-images.githubusercontent.com/5049680/133066678-6556ff17-992f-4400-b429-0a2b85df60b2.png">
<img width="871" alt="Screenshot 2021-09-13 at 11 12 42" src="https://user-images.githubusercontent.com/5049680/133066687-59faebb2-a0da-4168-9b27-89b59ac65ac1.png">
<img width="872" alt="Screenshot 2021-09-13 at 11 12 55" src="https://user-images.githubusercontent.com/5049680/133066696-4f6f5a93-ac99-4319-8ec9-7cc097441d32.png">

**Comment by Edijae** [comment]
> Here is how I fixed this for our app. Sorry that these are screenshots, but our repo is private.
> <img alt="Screenshot 2021-09-13 at 11 09 51" width="890" src="https://user-images.githubusercontent.com/5049680/133066567-b01affd4-6dc8-45dc-9226-791bf11d49f5.png">
> <img alt="Screenshot 2021-09-13 at 11 10 25" width="873" src="https://user-images.githubusercontent.com/5049680/133066616-39748f9c-5061-48c5-a2d3-f42fcbdbd612.png">
> <img alt="Screenshot 2021-09-13 at 11 10 53" width="869" src="https://user-images.githubusercontent.com/5049680/133066635-c6d9c374-0fff-4958-a1d5-12ef2f105e3a.png">
> <img alt="Screenshot 2021-09-13 at 11 11 09" width="872" src="https://user-images.githubusercontent.com/5049680/133066652-a085643c-8093-49be-89da-fb90a2c9f25e.png">
> <img alt="Screenshot 2021-09-13 at 11 11 45" width="872" src="https://user-images.githubusercontent.com/5049680/133066672-42be87ba-469b-4481-bac6-ac9a2c10d76d.png">
> <img alt="Screenshot 2021-09-13 at 11 12 11" width="868" src="https://user-images.githubusercontent.com/5049680/133066678-6556ff17-992f-4400-b429-0a2b85df60b2.png">
> <img alt="Screenshot 2021-09-13 at 11 12 42" width="871" src="https://user-images.githubusercontent.com/5049680/133066687-59faebb2-a0da-4168-9b27-89b59ac65ac1.png">
> <img alt="Screenshot 2021-09-13 at 11 12 55" width="872" src="https://user-images.githubusercontent.com/5049680/133066696-4f6f5a93-ac99-4319-8ec9-7cc097441d32.png">

@c4augustus the test for this was failing  with `org.mockito.exceptions.verification.NoInteractionsWanted:  No interactions wanted here But found this interaction on mock 'sSLContext'`

```
verifyNoMoreInteractions(
                SSLContext::class.java,
                Platform::class.java,
                sslSocketMock,
                sslContextMock,
                sslSocketFactoryMock,
                platformMock,
                inetAddressMock,
                localInetAddressMock
        )
```

**Comment by CyxouD** [comment]
@gotev for me to work (on a specific device without Google Play Services), I had to call `sc.init(null, trustManager, null)` instead of `sc.init(null, null, null)`, where `trustManager` is your custom trust manager which extends `X509TrustManager`. The key point is to write it secure and make `checkServerTrusted` to accept your server.
