### ISSUE TITLE
CI failures for Corretto Platform

### ISSUE THREAD

**Issue by yschimke** [square/okhttp#5592]
Ultra low priority but trying to dig in

https://app.circleci.com/jobs/github/square/okhttp/6903

https://circleci.com/api/v1.1/project/github/square/okhttp/6903/output/103/0?file=true

Not sure if it's resource issue, or failing to negotiate HTTP/2 etc.

**Comment by yschimke** [comment]
Not going to prioritise this, I think enough to have support for running with this platform outside of CI.  And commit resources once we see active reports.

**Comment by yschimke** [comment]
Will reopen on first active user

**Comment by SalusaSecondus** [comment]
We've just released version 1.5.0 and I'm guessing prior tests were done with 1.2.0 or older.  Is this worth re-checking?

Also, as a maintainer of the [Amazon Corretto Crypto Provider](https://github.com/corretto/amazon-corretto-crypto-provider) I'd love if you could provide me with a repro case. You may not be using ACCP yet, but we want to ensure that it works for everyone. So, any potential bugs or hiccups need to be tracked down. Thank you!

**Comment by yschimke** [comment]
Here is a PR building against the Corretto Crypto provider on OpenJDK 8 and 11.  I guess there is also builds we could do against the Corretto OpenJDK itself.  

https://github.com/square/okhttp/pull/6266

How do most people experience this provider? Opt-in for high performance, like people adopting Conscrypt?

Or do people get this by default in AWS?

**Comment by yschimke** [comment]
Failing with JDK8

**Comment by yschimke** [comment]
@SalusaSecondus I think the current assumptions in the platform test code are incorrect.  If I understand correctly, Corretto won't enable HTTP/2 pre JDK8u252.  But regardless of the JDK will change from the internal ciphers and hashes 

The test code green lights HTTP/2 because it sees Corretto, but that will still fail because of this requirement of SSLSocket.

```
      isAvailable = if (majorVersion != null) {
        majorVersion >= 9
      } else {
        try {
          // also present on JDK8 after build 252.
          SSLSocket::class.java.getMethod("getApplicationProtocol")
          true
        } catch (nsme: NoSuchMethodException) {
          false
        }
      }
```

**Comment by yschimke** [comment]
@SalusaSecondus Does Corretto on JDK8 < u252 work with ALPN Boot?  Is it completely unrelated, i.e. you wouldn't expect any issues?

**Comment by SalusaSecondus** [comment]
Thanks. I'll look through that PR. While I do so, some potentially helpful notes:
* The [Amazon Corretto Crypto Provider (ACCP)](https://github.com/corretto/amazon-corretto-crypto-provider) is a standalone JCE cryptographic provider which many people use on their systems.
* There is [Amazon Corretto](https://docs.aws.amazon.com/corretto/), a distribution of the OpenJDK.
* ACCP and Corretto share people, resources, and names, but are mostly unrelated. Many people take one without the other.
* Right now ACCP is not a JSSE provider and so doesn't enable any TLS specific logic. So, HTTP/2 support must come from your other JSSE providers (such as the Java default one or BouncyCastle). The cryptography can still be accelerated by ACCP though.

So, I think your post about the current test assumptions being wrong is likely correct.

I'll keep digging and try to figure out exactly what's happening here though. Thank you for the information.

**Comment by yschimke** [comment]
At the moment, I don't know of a live bug with JDK11+ACCP. 

JDK8+ACCP is probably working once I fix OkHttp tests, but also questionable why you would bother.  Why adopt a new Crypto provider but live with pre-ALPN HTTP/1.1 in your client.

**Comment by SalusaSecondus** [comment]
Glad to hear that things aren't broken.

As for why? I don't know enough about `okhttp` to speak to that. I just wanted to make sure we weren't accidentally breaking anything. (Feel free to re-close this.)
